variables:
  - group: GitHub

pool:
  vmImage: 'macOS-10.13'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - task: Npm@1
    inputs:
      command: 'install'

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'run build'

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'run package'

  - task: CopyFiles@2
    inputs:
      Contents: |
        'electron-build/SG Dial Sim*.exe'
        'electron-build/SG Dial Sim*.dmg'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'Electron executables'
      targetPath: '$(Build.ArtifactStagingDirectory)'
