variables:
  - group: GitHub

pool:
  vmImage: 'macOS-10.13'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - task: Npm@1
    inputs:
      command: 'install'

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'run build'

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'run package'

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'Windows build'
      targetPath: 'electron-build/SG Dial Sim.exe'

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'Mac build'
      targetPath: 'electron-build/SG Dial Sim.dmg'
