pool:
  vmImage: 'macOS-10.13'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - task: Npm@1
    inputs:
      command: 'install'

  - script: |
      npm run build
    displayName: 'Build artifacts'
