variables:
    - group: GitHub

pool:
    vmImage: "macOS-10.15"

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: "10.x"
      displayName: "Install Node.js"

    - task: Npm@1
      inputs:
          command: "custom"
          customCommand: "ci"

    - task: Npm@1
      inputs:
          command: "custom"
          customCommand: "run build"

    - task: InstallAppleCertificate@2
      inputs:
          certSecureFile: "DeveloperID.p12"
          certPwd: "$(P12password)"

    - task: Npm@1
      inputs:
          command: "custom"
          customCommand: "run package"
      env:
          APPLEID: $(AppleID)
          APPLEIDPASS: $(AppleIDPass)

    - task: CopyFiles@2
      inputs:
          SourceFolder: "electron-build"
          Contents: |
              *.exe
              *.dmg
          TargetFolder: "$(Build.ArtifactStagingDirectory)"

    - task: PublishPipelineArtifact@0
      inputs:
          artifactName: "Electron executables"
          targetPath: "$(Build.ArtifactStagingDirectory)"
